# Generated by Django 3.2.15 on 2024-08-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20240630_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("none", "None"),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("gluten-Free", "Gluten-free"),
                    ("other but specify", "Other but Specify"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                    ("other", "Other"),
                    ("no-answer", "Prefer not to answer"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="tshirt_size",
            field=models.CharField(
                choices=[(None, ""), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("asian-indian", "Asian Indian"),
                    ("black-african-american", "Black or African American"),
                    ("chinese", "Chinese"),
                    ("filipino", "Filipino"),
                    ("guamanian-chamorro", "Guamanian or Chamorro"),
                    ("hispanic-latino", "Hispanic/Latino/Spanish Origin"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("middle-eastern", "Middle Eastern"),
                    ("native-american", "Native American or Alaskan Native"),
                    ("native-hawaiian", "Native Hawaiian"),
                    ("samoan", "Samoan"),
                    ("vietnamese", "Vietnamese"),
                    ("caucasian", "White / Caucasian"),
                    ("other-asian", "Other Asian (Thai, Cambodian, etc)"),
                    ("other-pacific-islander", "Other Pacific Islander"),
                    ("other", "Other (Please Specify)"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
            ),
        ),
    ]
