# Generated by Django 3.2.15 on 2024-09-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_revert_0007_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='free_response_pronouns',
            field=models.CharField(default='', help_text="If you selected 'Other', please specify your pronouns.", max_length=20),
        ),
    ]
