# Generated by Django 3.2.15 on 2024-09-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registration", "0008_revert_0007_changes")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("none", "None"),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("celiac-disease", "Celiac Disease"),
                    ("allergies", "Allergies"),
                    ("kosher", "Kosher"),
                    ("gluten-free", "Gluten Free"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_dietary_restrictions",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you selected 'Allergies' or 'Other', please specify.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_gender",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you selected 'Prefer to Self-Describe', please specify.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_highest_formal_education",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you selected 'Other' for education, please specify.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_pronouns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If selected 'Other', please specify",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_sexual_identity",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you selected 'Different Identity', please specify.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("man", "Man"),
                    ("woman", "Woman"),
                    ("non-binary", "Non-Binary"),
                    ("prefer-to-self-describe", "Prefer to Self-Describe"),
                    ("prefer-to-not-answer", "Prefer to not Answer"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="highest_formal_education",
            field=models.CharField(
                choices=[
                    (None, ""),
                    (
                        "less-than-secondary-or-high-school",
                        "Less than Secondary / High School",
                    ),
                    ("secondary-or-high-school", "Secondary / High School"),
                    (
                        "post-secondary-2-years",
                        "2 year Undergraduate University or community college program",
                    ),
                    (
                        "post-secondary-3-or-more-years",
                        "3+ year Undergraduate University program",
                    ),
                    (
                        "graduate-university",
                        "Graduate University (Masters, Professional, Doctoral, etc)",
                    ),
                    ("code-school-or-bootcamp", "Code School / Bootcamp"),
                    (
                        "vocational-or-trades-or-apprenticeship",
                        "Other Vocational or Trade Program or Apprenticeship",
                    ),
                    ("other", "Other"),
                    ("prefer-to-not-answer", "Prefer to not answer"),
                ],
                default="",
                help_text="What is your highest level of education completed?",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="how_many_hackathons",
            field=models.TextField(
                choices=[
                    (None, ""),
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5 or more", "5 or more"),
                ],
                default="",
                help_text="How many hackathons have you been to?",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="sexual_identity",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("heterosexual-or-straight", "Heterosexual or straight"),
                    ("gay-or-lesbian", "Gay or lesbian"),
                    ("bisexual", "Bisexual"),
                    ("different-identity", "Different Identity"),
                    ("prefer-to-not-answer", "Prefer to not Answer"),
                ],
                default="",
                help_text="Do you consider yourself to be any of the following?",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tshirt_size",
            field=models.CharField(
                choices=[(None, ""), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="under_represented_group",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("unsure", "Unsure"),
                ],
                default="",
                help_text="Are you in an underrepresented group in tech?",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, ""),
                    ("american-native", "American Indian or Alaskan Native"),
                    ("asian-pacific-islander", "Asian / Pacific Islander"),
                    ("black-african-american", "Black or African American"),
                    ("hispanic", "Hispanic"),
                    ("caucasian", "White / Caucasian"),
                    ("other", "Multiple ethnicity / Other"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="pronouns",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("he-him", "he/him"),
                    ("he-they", "he/they"),
                    ("she-her", "she/her"),
                    ("she-they", "she/they"),
                    ("they-them", "they/them"),
                    ("other", "other"),
                    ("no-answer", "prefer not to answer"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="study_level",
            field=models.CharField(
                choices=[
                    (None, ""),
                    (
                        "post-secondary-2-years",
                        "2 year Undergraduate University or community college program",
                    ),
                    (
                        "post-secondary-3-or-more-years",
                        "3+ year Undergraduate University program",
                    ),
                    (
                        "graduate",
                        "Graduate University (Masters, Professional, Doctoral, etc)",
                    ),
                    ("other", "Other"),
                ],
                help_text="Current level of study",
                max_length=50,
            ),
        ),
    ]
