# Generated by Django 3.2.15 on 2024-09-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registration", "0008_revert_0007_changes")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("none", "None"),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("celiac-disease", "Celiac Disease"),
                    ("allergies", "Allergies"),
                    ("kosher", "Kosher"),
                    ("gluten-free", "Gluten Free"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_dietary_restrictions",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you selected 'Allergies' or 'Other', please specify.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_gender",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If you selected 'Prefer to Self-Describe', please specify.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="free_response_pronouns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If selected 'Other', please specify",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("man", "Man"),
                    ("woman", "Woman"),
                    ("non-binary", "Non-Binary"),
                    ("prefer-to-self-describe", "Prefer to Self-Describe"),
                    ("prefer-to-not-answer", "Prefer to not Answer"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tshirt_size",
            field=models.CharField(
                choices=[(None, ""), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="under_represented_group",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("unsure", "Unsure"),
                ],
                default="",
                help_text="Are you in an underrepresented group in tech?",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, ""),
                    ("american-native", "American Indian or Alaskan Native"),
                    ("asian-pacific-islander", "Asian / Pacific Islander"),
                    ("black-african-american", "Black or African American"),
                    ("hispanic", "Hispanic"),
                    ("caucasian", "White / Caucasian"),
                    ("other", "Multiple ethnicity / Other"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="pronouns",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("he-him", "he/him"),
                    ("he-they", "he/they"),
                    ("she-her", "she/her"),
                    ("she-they", "she/they"),
                    ("they-them", "they/them"),
                    ("other", "other"),
                    ("no-answer", "prefer not to answer"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
